#!/bin/sh

# Enable firewall offloading/NSS-friendly defaults for ER1 LEDE.
# Do not force CPU governor; keep upstream/default CPU frequency policy.

uci -q batch <<'UCI'
set firewall.@defaults[0].flow_offloading='1'
set firewall.@defaults[0].flow_offloading_hw='1'
set firewall.@defaults[0].fullcone='1'
commit firewall
UCI

# Make sure qca-nss-ecm is enabled when present.
if [ -x /etc/init.d/qca-nss-ecm ]; then
    /etc/init.d/qca-nss-ecm enable
fi

exit 0
